/**
 * Button positions detected from phone_canvas.png
 * Auto-generated by detect_buttons_simple.py
 * 
 * The phone canvas has 17 orange button regions detected.
 * Positions are in percentages relative to the image size (1280x669)
 */

export interface ButtonPosition {
  id: number;
  centerX: string;
  centerY: string;
  width: string;
  height: string;
  key?: string; // Keyboard key to simulate
  label?: string; // Button label
}

// Raw detected button positions
export const DETECTED_BUTTON_POSITIONS: ButtonPosition[] = [
  { // Button 1 - Top center (likely screen area or top button)
    id: 1,
    centerX: '49.30%',
    centerY: '59.19%',
    width: '7.34%',
    height: '2.99%',
  },
  { // Button 2 - Left action button
    id: 2,
    centerX: '43.98%',
    centerY: '61.73%',
    width: '4.22%',
    height: '6.88%',
    key: 'z',
    label: 'A',
  },
  { // Button 3 - Right action button
    id: 3,
    centerX: '53.91%',
    centerY: '62.63%',
    width: '5.94%',
    height: '8.67%',
    key: 'x',
    label: 'B',
  },
  { // Button 4 - Small center element
    id: 4,
    centerX: '49.38%',
    centerY: '69.66%',
    width: '1.88%',
    height: '0.00%',
  },
  { // Button 5 - Numpad 4 (Left)
    id: 5,
    centerX: '42.97%',
    centerY: '70.10%',
    width: '4.06%',
    height: '3.89%',
    key: 'ArrowLeft',
    label: '4',
  },
  { // Button 6 - Numpad 6 (Right)
    id: 6,
    centerX: '55.78%',
    centerY: '70.10%',
    width: '4.06%',
    height: '3.89%',
    key: 'ArrowRight',
    label: '6',
  },
  { // Button 7 - Numpad 2 (Up) - center top row
    id: 7,
    centerX: '49.30%',
    centerY: '71.45%',
    width: '4.22%',
    height: '2.99%',
    key: 'ArrowUp',
    label: '2',
  },
  { // Button 8 - Small center element
    id: 8,
    centerX: '49.38%',
    centerY: '75.34%',
    width: '1.56%',
    height: '0.00%',
  },
  { // Button 9 - Numpad 1
    id: 9,
    centerX: '43.12%',
    centerY: '75.64%',
    width: '4.06%',
    height: '3.59%',
    label: '1',
  },
  { // Button 10 - Numpad 3
    id: 10,
    centerX: '55.62%',
    centerY: '75.78%',
    width: '4.06%',
    height: '3.89%',
    label: '3',
  },
  { // Button 11 - Numpad 5 (center)
    id: 11,
    centerX: '49.38%',
    centerY: '77.28%',
    width: '4.38%',
    height: '3.29%',
    label: '5',
  },
  { // Button 12 - Numpad 7
    id: 12,
    centerX: '43.28%',
    centerY: '81.46%',
    width: '4.06%',
    height: '3.89%',
    label: '7',
  },
  { // Button 13 - Numpad 9
    id: 13,
    centerX: '55.39%',
    centerY: '81.61%',
    width: '3.91%',
    height: '4.19%',
    label: '9',
  },
  { // Button 14 - Numpad 8 (Down)
    id: 14,
    centerX: '49.38%',
    centerY: '82.96%',
    width: '4.38%',
    height: '3.29%',
    key: 'ArrowDown',
    label: '8',
  },
  { // Button 15 - Numpad * (star)
    id: 15,
    centerX: '43.59%',
    centerY: '87.44%',
    width: '4.06%',
    height: '3.89%',
    label: '*',
  },
  { // Button 16 - Numpad # (hash)
    id: 16,
    centerX: '55.08%',
    centerY: '87.44%',
    width: '4.22%',
    height: '4.48%',
    label: '#',
  },
  { // Button 17 - Numpad 0
    id: 17,
    centerX: '49.38%',
    centerY: '88.94%',
    width: '4.06%',
    height: '3.29%',
    label: '0',
  },
];

// Filtered buttons for game controls (with key mappings)
export const GAME_CONTROL_BUTTONS = DETECTED_BUTTON_POSITIONS.filter(btn => btn.key);

// Button mapping by function
export const BUTTON_MAP = {
  ACTION_A: DETECTED_BUTTON_POSITIONS[1], // Button 2
  ACTION_B: DETECTED_BUTTON_POSITIONS[2], // Button 3
  DPAD_UP: DETECTED_BUTTON_POSITIONS[6], // Button 7 (2 key)
  DPAD_DOWN: DETECTED_BUTTON_POSITIONS[13], // Button 14 (8 key)
  DPAD_LEFT: DETECTED_BUTTON_POSITIONS[4], // Button 5 (4 key)
  DPAD_RIGHT: DETECTED_BUTTON_POSITIONS[5], // Button 6 (6 key)
};
